### ISSUE TITLE
func verticalSpacing might contain a mistake

### ISSUE THREAD

**Issue by GerdC** [ksemianov/WrappingHStack#1]
The current implementation of `func verticalSpacing` is:

    private func horizontalSpacing(_ lhs: LayoutSubview, _ rhs: LayoutSubview) -> CGFloat {
        if let horizontalSpacing { return horizontalSpacing }

        return lhs.spacing.distance(to: rhs.spacing, along: .horizontal)
    }

    private func verticalSpacing(_ lhs: LayoutSubview, _ rhs: LayoutSubview) -> CGFloat {
        if let verticalSpacing { return verticalSpacing }

        return lhs.spacing.distance(to: rhs.spacing, along: .horizontal)
    }

This looks like a copy & paste bug from `func horizontalSpacing`.

Shouldn't the code read

    private func verticalSpacing(_ lhs: LayoutSubview, _ rhs: LayoutSubview) -> CGFloat {
        if let verticalSpacing { return verticalSpacing }

        return lhs.spacing.distance(to: rhs.spacing, along: .vertical)
    }

**Comment by ksemianov** [comment]
Thank you for noticing! Indeed, it seems to be a typo. I've applied a fix.
