### ISSUE TITLE
What is layoutProperties used for?

### ISSUE THREAD

**Issue by break2k** [ksemianov/WrappingHStack#3]
See the attached screenshot and the linked line.

![image](https://github.com/ksemianov/WrappingHStack/assets/506722/5573792f-2674-47ea-8c1e-f79ec1645d5a)

https://github.com/ksemianov/WrappingHStack/blob/main/Sources/WrappingHStack/WrappingHStack.swift#L36

**Comment by ksemianov** [comment]
[LayoutProperties](https://developer.apple.com/documentation/swiftui/layoutproperties) is one of the optional [Layout protocol](https://developer.apple.com/documentation/swiftui/layout) requirements. In theory, it might help SwiftUI's layouting engine to make better size proposals. However, I haven't observed any difference with default values.
